spring:
  application:
    name: eureka-backend-demo
server:
  port: 9000
eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${spring.application.name}:${server.port}